
# // data to be posted on user sign up
# POST http://localhost:3000/api/auth/user/signUp HTTP/1.1
# content-type: application/json

# {
#     "name":"Pankaj Shukla",
#     "RegNo":"18BIT0485",
#     "email":"pankaj.shukla2018@vitstudent.ac.in",
#     "mobileNo":7089212082,
#     "BlockName":"C",
#     "RoomNo":202,
#     "ClubCode":10001,
#     "password":"pankajShukla"
# } 

# POST http://localhost:3000/api/auth/user/logIn HTTP/1.1
# content-type:application/json

# {
#     "RegNo":"18BIT0485",
#     "password":"pankajShukla"
#  }


# POST http://localhost:3000/api/auth/org/signUp HTTP/1.1
# Content-Type: application/json

# {
#     "ClubName":"MSTC",
#     "Email":"pankajshuklajavacoder@gmail.com",
#     "MobileNo":12346,
#     "ExpectedCandidates":2,
#     "Extras":"no",
#     "password":"mstc"
# }


# POST http://localhost:3000/api/auth/org/logIn HTTP/1.1
# Content-Type: application/json

# {
#     "ClubCode":"1000",
#     "password":"mstc"
# }

# POST http://localhost:3000/api/post/org/checkResult HTTP/1.1
# Content-Type: application/json

# {
#      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDbHViQ29kZSI6MTAwMCwiQ2x1Yk5hbWUiOiJNU1RDIiwiaWF0IjoxNTkyMTI3NDI0LCJleHAiOjE1OTIxMzEwMjR9.tslOeo-HWvinuhkVwF0JxfAZph-WJuQM0puetsD8RFI",
#     "ClubCode":"1000",
#     "password":"mstc",
#     "testId":"1000"
# }


# POST http://localhost:3000/api/post/org/addTest HTTP/1.1
# Content-Type: application/json

# {
#     "ClubCode":1000,
#     "testId":1000,
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDbHViQ29kZSI6MTAwMCwiQ2x1Yk5hbWUiOiJNU1RDIiwiaWF0IjoxNTkyMTI0MDEyLCJleHAiOjE1OTIxMjc2MTJ9.pPj--SJuuHgqa4OHSllOPuv6u-cpqcXgSbGHE1d6kK8"
# }


# POST http://localhost:3000/api/post/org/questions/:id HTTP/1.1
# Content-Type: application/json

# {
#     "ClubCode":1000,
#     "testId":1000,
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDbHViQ29kZSI6MTAwMCwiQ2x1Yk5hbWUiOiJNU1RDIiwiaWF0IjoxNTkyODIwODkxLCJleHAiOjE1OTI4MjQ0OTF9.EVveLRLYMW5pBTy4385UcaLMNfNykQmA7WkwUvHXCHY",
#     "question":
#         {
# 		 "ques":"What is full form of MSTC ?",  	
# 		 "ans":"STC",
# 		 "options":["student  center","STC","student dc"]
#          }		
 	
# }

// remeber in this route you only need to put the part which is to be updated
// no need to put all the part
// id is compulsory in url part

# PUT http://localhost:3000/api/post/org/questions/:id HTTP/1.1
# Content-Type: application/json

# {
#     "ClubCode":1000,
#     "testId":1000,
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDbHViQ29kZSI6MTAwMCwiQ2x1Yk5hbWUiOiJNU1RDIiwiaWF0IjoxNTkyODIwODkxLCJleHAiOjE1OTI4MjQ0OTF9.EVveLRLYMW5pBTy4385UcaLMNfNykQmA7WkwUvHXCHY",
#     "question":
#         {
#          "options":["BATCH OF IT"],
# 		 "ques":"What is full form of BAKARBAZI ?",  	
# 		 "ans":"BATCH OF IT"
#          }		
 	
# }


# DELETE  http://localhost:3000/api/post/org/questions/:id HTTP/1.1
# Content-Type: application/json

# {
#     "ClubCode":1000,
#     "testId":1000,
#      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDbHViQ29kZSI6MTAwMCwiQ2x1Yk5hbWUiOiJNU1RDIiwiaWF0IjoxNTkyODIwODkxLCJleHAiOjE1OTI4MjQ0OTF9.EVveLRLYMW5pBTy4385UcaLMNfNykQmA7WkwUvHXCHY"
# }




# POST  http://localhost:3000/api/post/user/takeTest HTTP/1.1
# Content-Type: application/json

# {
#     "testId":1000,
#     "ClubCode":1000,
#     "RegNo":"18BIT0485",
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSZWdObyI6IjE4QklUMDQ4NSIsIk5hbWUiOiJQYW5rYWogU2h1a2xhIiwiaWF0IjoxNTkxMDEzMzk5LCJleHAiOjE1OTEwMTQyOTl9.F1yU8jcA3iyzL_1o0UAL4qw1mqLSreL1HEXOxdsWqfY"
# }

# POST http://localhost:3000/api/post/user/submitTest HTTP/1.1
# Content-Type: application/json

# {

#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSZWdObyI6IjE4QklUMDQ4NSIsIk5hbWUiOiJQYW5rYWogU2h1a2xhIiwiaWF0IjoxNTkyMjI1MzQ4LCJleHAiOjE1OTIyMjYyNDh9.RKvWuYfichGyLzrSvMmn8To2l0PLH42ecX6w2OUQsp4",
#     "testId":1000,
#     "RegNo":"18BIT0485",
#     "Name":"Pankaj Shukla",
#     "ClubCode":1000,
#     "ClubName":"MSTC",
#     "ans":[{"1","STC"}]
# }